package mhfc.net.client.model.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDeviljhoArmor extends ModelBiped
{
  //fields
    ModelRenderer ha;
    ModelRenderer hb;
    ModelRenderer hc;
    ModelRenderer hd;
    ModelRenderer he;
    ModelRenderer hf;
    ModelRenderer hg;
    ModelRenderer hh;
    ModelRenderer hi;
    ModelRenderer hj;
    ModelRenderer hk;
    ModelRenderer hl;
    ModelRenderer hm;
    ModelRenderer hn;
    ModelRenderer ho;
    ModelRenderer hp;
    ModelRenderer hq;
    ModelRenderer hr;
    ModelRenderer hs;
    ModelRenderer ht;
    ModelRenderer hu;
    ModelRenderer hv;
    ModelRenderer hw;
    ModelRenderer hx;
    ModelRenderer hy;
    ModelRenderer hz;
    ModelRenderer h1;
    ModelRenderer h2;
    ModelRenderer ba;
    ModelRenderer bb;
    ModelRenderer bc;
    ModelRenderer bd;
    ModelRenderer be;
    ModelRenderer bf;
    ModelRenderer bg;
    ModelRenderer bi;
    ModelRenderer bj;
    ModelRenderer la;
    ModelRenderer lb;
    ModelRenderer lc;
    ModelRenderer ld;
    ModelRenderer le;
    ModelRenderer lf;
    ModelRenderer lg;
    ModelRenderer lh;
    ModelRenderer li;
    ModelRenderer lj;
    ModelRenderer ll;
    ModelRenderer ra;
    ModelRenderer rb;
    ModelRenderer rc;
    ModelRenderer rd;
    ModelRenderer re;
    ModelRenderer rf;
    ModelRenderer rg;
    ModelRenderer rh;
    ModelRenderer rfa;
    ModelRenderer rfb;
    ModelRenderer lfa;
    ModelRenderer lfb;
  
  public ModelDeviljhoArmor(float f)
  {
	  super(f, 0, 128, 128);
	  textureWidth = 128;
	  textureHeight = 128;
      ha = new ModelRenderer(this, 0, 43);
      ha.addBox(-4.5F, -4F, -5F, 4, 4, 1);
      ha.setRotationPoint(0F, 0F, 0F);
      ha.setTextureSize(128, 128);
      ha.mirror = true;
      setRotation(ha, 0F, 0F, 0F);
      hb = new ModelRenderer(this, 0, 43);
      hb.addBox(0.5F, -4F, -5F, 4, 4, 1);
      hb.setRotationPoint(0F, 0F, 0F);
      hb.setTextureSize(128, 128);
      hb.mirror = true;
      setRotation(hb, 0F, 0F, 0F);
      hc = new ModelRenderer(this, 0, 49);
      hc.addBox(-1.5F, -4.1F, -5.2F, 3, 1, 1);
      hc.setRotationPoint(0F, 0F, 0F);
      hc.setTextureSize(128, 128);
      hc.mirror = true;
      setRotation(hc, 0F, 0F, 0F);
      hd = new ModelRenderer(this, 0, 52);
      hd.addBox(-1F, -3F, -5.4F, 2, 3, 2);
      hd.setRotationPoint(0F, 0F, 0F);
      hd.setTextureSize(128, 128);
      hd.mirror = true;
      setRotation(hd, 0F, 0F, 0F);
      he = new ModelRenderer(this, 0, 58);
      he.addBox(1F, -5F, -5F, 3, 1, 1);
      he.setRotationPoint(0F, 0F, 0F);
      he.setTextureSize(128, 128);
      he.mirror = true;
      setRotation(he, 0F, 0F, 0F);
      hf = new ModelRenderer(this, 0, 58);
      hf.addBox(-4F, -5F, -5F, 3, 1, 1);
      hf.setRotationPoint(0F, 0F, 0F);
      hf.setTextureSize(128, 128);
      hf.mirror = true;
      setRotation(hf, 0F, 0F, 0F);
      hg = new ModelRenderer(this, 9, 52);
      hg.addBox(-1F, -10.5F, -5F, 2, 6, 1);
      hg.setRotationPoint(0F, 0F, 0F);
      hg.setTextureSize(128, 128);
      hg.mirror = true;
      setRotation(hg, 0F, 0F, 0F);
      hh = new ModelRenderer(this, 0, 61);
      hh.addBox(-4.6F, -5F, -4F, 1, 5, 8);
      hh.setRotationPoint(0F, 0F, 0F);
      hh.setTextureSize(128, 128);
      hh.mirror = true;
      setRotation(hh, 0F, 0F, 0F);
      hi = new ModelRenderer(this, 0, 61);
      hi.addBox(3.6F, -5F, -4F, 1, 5, 8);
      hi.setRotationPoint(0F, 0F, 0F);
      hi.setTextureSize(128, 128);
      hi.mirror = true;
      setRotation(hi, 0F, 0F, 0F);
      hj = new ModelRenderer(this, 0, 76);
      hj.addBox(3.6F, -8F, -4.7F, 1, 2, 9);
      hj.setRotationPoint(0F, 0F, 0F);
      hj.setTextureSize(128, 128);
      hj.mirror = true;
      setRotation(hj, 0F, 0F, 0F);
      hk = new ModelRenderer(this, 0, 76);
      hk.addBox(-4.6F, -8F, -4.7F, 1, 2, 9);
      hk.setRotationPoint(0F, 0F, 0F);
      hk.setTextureSize(128, 128);
      hk.mirror = true;
      setRotation(hk, 0F, 0F, 0F);
      hl = new ModelRenderer(this, 0, 88);
      hl.addBox(-2.5F, -11F, -4F, 5, 3, 8);
      hl.setRotationPoint(0F, 0F, 0F);
      hl.setTextureSize(128, 128);
      hl.mirror = true;
      setRotation(hl, 0F, 0F, 0F);
      hm = new ModelRenderer(this, 0, 100);
      hm.addBox(-1F, -12.5F, -5F, 2, 2, 10);
      hm.setRotationPoint(0F, 0F, 0F);
      hm.setTextureSize(128, 128);
      hm.mirror = true;
      setRotation(hm, 0F, 0F, 0F);
      hn = new ModelRenderer(this, 12, 45);
      hn.addBox(4F, -7.5F, 2F, 1, 1, 1);
      hn.setRotationPoint(0F, 0F, 0F);
      hn.setTextureSize(128, 128);
      hn.mirror = true;
      setRotation(hn, 0.7853982F, 0F, 0F);
      ho = new ModelRenderer(this, 12, 45);
      ho.addBox(-5F, -7.5F, 2F, 1, 1, 1);
      ho.setRotationPoint(0F, 0F, 0F);
      ho.setTextureSize(128, 128);
      ho.mirror = true;
      setRotation(ho, 0.7853982F, 0F, 0F);
      hp = new ModelRenderer(this, 12, 49);
      hp.addBox(3F, -3.7F, -5.5F, 1, 1, 1);
      hp.setRotationPoint(0F, 0F, 0F);
      hp.setTextureSize(128, 128);
      hp.mirror = true;
      setRotation(hp, 0F, 0F, 0F);
      hq = new ModelRenderer(this, 12, 49);
      hq.addBox(1.6F, -2.7F, -5.5F, 1, 1, 1);
      hq.setRotationPoint(0F, 0F, 0F);
      hq.setTextureSize(128, 128);
      hq.mirror = true;
      setRotation(hq, 0F, 0F, 0F);
      hr = new ModelRenderer(this, 12, 49);
      hr.addBox(3F, -1.7F, -5.5F, 1, 1, 1);
      hr.setRotationPoint(0F, 0F, 0F);
      hr.setTextureSize(128, 128);
      hr.mirror = true;
      setRotation(hr, 0F, 0F, 0F);
      hs = new ModelRenderer(this, 12, 49);
      hs.addBox(-4F, -3.7F, -5.5F, 1, 1, 1);
      hs.setRotationPoint(0F, 0F, 0F);
      hs.setTextureSize(128, 128);
      hs.mirror = true;
      setRotation(hs, 0F, 0F, 0F);
      ht = new ModelRenderer(this, 12, 49);
      ht.addBox(-2.6F, -2.7F, -5.5F, 1, 1, 1);
      ht.setRotationPoint(0F, 0F, 0F);
      ht.setTextureSize(128, 128);
      ht.mirror = true;
      setRotation(ht, 0F, 0F, 0F);
      hu = new ModelRenderer(this, 12, 49);
      hu.addBox(-4F, -1.7F, -5.5F, 1, 1, 1);
      hu.setRotationPoint(0F, 0F, 0F);
      hu.setTextureSize(128, 128);
      hu.mirror = true;
      setRotation(hu, 0F, 0F, 0F);
      hv = new ModelRenderer(this, 0, 113);
      hv.addBox(-4F, -8F, -4.8F, 4, 2, 1);
      hv.setRotationPoint(0F, 0F, 0F);
      hv.setTextureSize(128, 128);
      hv.mirror = true;
      setRotation(hv, 0F, 0F, 0F);
      hw = new ModelRenderer(this, 12, 113);
      hw.addBox(0F, -8F, -4.8F, 4, 2, 1);
      hw.setRotationPoint(0F, 0F, 0F);
      hw.setTextureSize(128, 128);
      hw.mirror = true;
      setRotation(hw, 0F, 0F, 0F);
      hx = new ModelRenderer(this, 0, 117);
      hx.addBox(-4.1F, -6.6F, -4.6F, 3, 1, 1);
      hx.setRotationPoint(0F, 0F, 0F);
      hx.setTextureSize(128, 128);
      hx.mirror = true;
      setRotation(hx, 0F, 0F, 0F);
      hy = new ModelRenderer(this, 0, 117);
      hy.addBox(1.1F, -6.6F, -4.6F, 3, 1, 1);
      hy.setRotationPoint(0F, 0F, 0F);
      hy.setTextureSize(128, 128);
      hy.mirror = true;
      setRotation(hy, 0F, 0F, 0F);
      hz = new ModelRenderer(this, 25, 113);
      hz.addBox(-4F, -10F, -4F, 2, 2, 8);
      hz.setRotationPoint(0F, 0F, 0F);
      hz.setTextureSize(128, 128);
      hz.mirror = true;
      setRotation(hz, 0F, 0F, 0F);
      h1 = new ModelRenderer(this, 25, 102);
      h1.addBox(2F, -10F, -4F, 2, 2, 8);
      h1.setRotationPoint(0F, 0F, 0F);
      h1.setTextureSize(128, 128);
      h1.mirror = true;
      setRotation(h1, 0F, 0F, 0F);
      h2 = new ModelRenderer(this, 0, 33);
      h2.addBox(-4F, -8F, 3.8F, 8, 8, 1);
      h2.setRotationPoint(0F, 0F, 0F);
      h2.setTextureSize(128, 128);
      h2.mirror = true;
      setRotation(h2, 0F, 0F, 0F);
      ba = new ModelRenderer(this, 27, 78);
      ba.addBox(-4F, 0.2F, -4F, 8, 6, 2);
      ba.setRotationPoint(0F, 0F, 0F);
      ba.setTextureSize(128, 128);
      ba.mirror = true;
      setRotation(ba, 0F, 0F, 0F);
      bb = new ModelRenderer(this, 27, 75);
      bb.addBox(-4F, 8F, -3.8F, 8, 1, 1);
      bb.setRotationPoint(0F, 0F, 0F);
      bb.setTextureSize(128, 128);
      bb.mirror = true;
      setRotation(bb, 0F, 0F, 0F);
      bc = new ModelRenderer(this, 27, 67);
      bc.addBox(-4.5F, -1.5F, -5.5F, 2, 5, 2);
      bc.setRotationPoint(0F, 0F, 0F);
      bc.setTextureSize(128, 128);
      bc.mirror = true;
      setRotation(bc, 0F, 0F, -0.5759587F);
      bd = new ModelRenderer(this, 36, 67);
      bd.addBox(2.5F, -1.5F, -5.5F, 2, 5, 2);
      bd.setRotationPoint(0F, 0F, 0F);
      bd.setTextureSize(128, 128);
      bd.mirror = true;
      setRotation(bd, 0F, 0F, 0.5759587F);
      be = new ModelRenderer(this, 27, 60);
      be.addBox(-4F, 6.1F, -3.2F, 8, 4, 2);
      be.setRotationPoint(0F, 0F, 0F);
      be.setTextureSize(128, 128);
      be.mirror = true;
      setRotation(be, 0F, 0F, 0F);
      bf = new ModelRenderer(this, 27, 56);
      bf.addBox(-7F, 5F, -4F, 2, 2, 1);
      bf.setRotationPoint(0F, 0F, 0F);
      bf.setTextureSize(128, 128);
      bf.mirror = true;
      setRotation(bf, 0F, 0F, -0.7853982F);
      bg = new ModelRenderer(this, 35, 56);
      bg.addBox(-3F, 6.5F, -3.8F, 1, 1, 1);
      bg.setRotationPoint(0F, 0F, 0F);
      bg.setTextureSize(128, 128);
      bg.mirror = true;
      setRotation(bg, 0F, 0F, 0F);
      bi = new ModelRenderer(this, 35, 56);
      bi.addBox(2F, 6.5F, -3.8F, 1, 1, 1);
      bi.setRotationPoint(0F, 0F, 0F);
      bi.setTextureSize(128, 128);
      bi.mirror = true;
      setRotation(bi, 0F, 0F, 0F);
      bj = new ModelRenderer(this, 27, 87);
      bj.addBox(-4F, 0F, 1.6F, 8, 11, 2);
      bj.setRotationPoint(0F, 0F, 0F);
      bj.setTextureSize(128, 128);
      bj.mirror = true;
      setRotation(bj, 0F, 0F, 0F);
      la = new ModelRenderer(this, 26, 33);
      la.addBox(-1F, -2.4F, -2.5F, 5, 5, 5);
      la.setRotationPoint(0F, 0F, 0F);
      la.setTextureSize(128, 128);
      la.mirror = true;
      setRotation(la, 0F, 0F, 0F);
      lb = new ModelRenderer(this, 27, 45);
      lb.addBox(0.5F, -3F, -3F, 2, 3, 3);
      lb.setRotationPoint(0F, 0F, 0F);
      lb.setTextureSize(128, 128);
      lb.mirror = true;
      setRotation(lb, -0.7853982F, 0F, 0F);
      lc = new ModelRenderer(this, 41, 52);
      lc.addBox(-1F, 2.5F, -2.4F, 4, 1, 1);
      lc.setRotationPoint(0F, 0F, 0F);
      lc.setTextureSize(128, 128);
      lc.mirror = true;
      setRotation(lc, 0F, 0F, 0F);
      ld = new ModelRenderer(this, 41, 52);
      ld.addBox(-1F, 2.5F, 1.4F, 4, 1, 1);
      ld.setRotationPoint(0F, 0F, 0F);
      ld.setTextureSize(128, 128);
      ld.mirror = true;
      setRotation(ld, 0F, 0F, 0F);
      le = new ModelRenderer(this, 27, 45);
      le.addBox(0.5F, 0F, -3F, 2, 3, 3);
      le.setRotationPoint(0F, 0F, 0F);
      le.setTextureSize(128, 128);
      le.mirror = true;
      setRotation(le, -0.7853982F, 0F, 0F);
      lf = new ModelRenderer(this, 27, 45);
      lf.addBox(0.5F, -3F, 0F, 2, 3, 3);
      lf.setRotationPoint(0F, 0F, 0F);
      lf.setTextureSize(128, 128);
      lf.mirror = true;
      setRotation(lf, -0.7853982F, 0F, 0F);
      lg = new ModelRenderer(this, 39, 45);
      lg.addBox(1F, 1F, -1F, 3, 3, 2);
      lg.setRotationPoint(0F, 0F, 0F);
      lg.setTextureSize(128, 128);
      lg.mirror = true;
      setRotation(lg, 0F, 0F, -0.7853982F);
      lh = new ModelRenderer(this, 50, 60);
      lh.addBox(2.6F, 2.5F, -2.5F, 1, 1, 5);
      lh.setRotationPoint(0F, 0F, 0F);
      lh.setTextureSize(128, 128);
      lh.mirror = true;
      setRotation(lh, 0F, 0F, 0F);
      li = new ModelRenderer(this, 49, 67);
      li.addBox(-1F, 3.5F, -2.8F, 5, 3, 1);
      li.setRotationPoint(0F, 0F, 0F);
      li.setTextureSize(128, 128);
      li.mirror = true;
      setRotation(li, 0F, 0F, 0F);
      lj = new ModelRenderer(this, 49, 67);
      lj.addBox(-1F, 3.5F, 1.8F, 5, 3, 1);
      lj.setRotationPoint(0F, 0F, 0F);
      lj.setTextureSize(128, 128);
      lj.mirror = true;
      setRotation(lj, 0F, 0F, 0F);
      ll = new ModelRenderer(this, 51, 43);
      ll.addBox(3.1F, 3.5F, -1.9F, 1, 3, 4);
      ll.setRotationPoint(0F, 0F, 0F);
      ll.setTextureSize(128, 128);
      ll.mirror = true;
      setRotation(ll, 0F, 0F, 0F);
      ra = new ModelRenderer(this, 26, 33);
      ra.addBox(-4F, -2.4F, -2.5F, 5, 5, 5);
      ra.setRotationPoint(0F, 0F, 0F);
      ra.setTextureSize(128, 128);
      ra.mirror = true;
      setRotation(ra, 0F, 0F, 0F);
      rb = new ModelRenderer(this, 27, 45);
      rb.addBox(-2.5F, -3F, -3F, 2, 3, 3);
      rb.setRotationPoint(0F, 0F, 0F);
      rb.setTextureSize(128, 128);
      rb.mirror = true;
      setRotation(rb, -0.7853982F, 0F, 0F);
      rc = new ModelRenderer(this, 41, 52);
      rc.addBox(-3F, 2.5F, -2.4F, 4, 1, 1);
      rc.setRotationPoint(0F, 0F, 0F);
      rc.setTextureSize(128, 128);
      rc.mirror = true;
      setRotation(rc, 0F, 0F, 0F);
      rd = new ModelRenderer(this, 41, 52);
      rd.addBox(-3F, 2.4F, 1.4F, 4, 1, 1);
      rd.setRotationPoint(0F, 0F, 0F);
      rd.setTextureSize(128, 128);
      rd.mirror = true;
      setRotation(rd, 0F, 0F, 0F);
      re = new ModelRenderer(this, 27, 45);
      re.addBox(-2.5F, 0F, -3F, 2, 3, 3);
      re.setRotationPoint(0F, 0F, 0F);
      re.setTextureSize(128, 128);
      re.mirror = true;
      setRotation(re, -0.7853982F, 0F, 0F);
      rf = new ModelRenderer(this, 27, 45);
      rf.addBox(-2.5F, -3F, 0F, 2, 3, 3);
      rf.setRotationPoint(0F, 0F, 0F);
      rf.setTextureSize(128, 128);
      rf.mirror = true;
      setRotation(rf, -0.7853982F, 0F, 0F);
      rg = new ModelRenderer(this, 39, 45);
      rg.addBox(-4F, -4F, -1F, 3, 3, 2);
      rg.setRotationPoint(0F, 0F, 0F);
      rg.setTextureSize(128, 128);
      rg.mirror = true;
      setRotation(rg, 0F, 0F, -0.7853982F);
      rh = new ModelRenderer(this, 50, 60);
      rh.addBox(-3.4F, 2.5F, -2.5F, 1, 1, 5);
      rh.setRotationPoint(0F, 0F, 0F);
      rh.setTextureSize(128, 128);
      rh.mirror = true;
      setRotation(rh, 0F, 0F, 0F);
      rfa = new ModelRenderer(this, 50, 75);
      rfa.addBox(-1.5F, 2.6F, -3.4F, 3, 8, 1);
      rfa.setRotationPoint(0F, 0F, 0F);
      rfa.setTextureSize(128, 128);
      rfa.mirror = true;
      setRotation(rfa, 0F, 0F, 0F);
      rfb = new ModelRenderer(this, 50, 86);
      rfb.addBox(-3F, 8F, -3.1F, 5, 4, 6);
      rfb.setRotationPoint(0F, 0F, 0F);
      rfb.setTextureSize(128, 128);
      rfb.mirror = true;
      setRotation(rfb, 0F, 0F, 0F);
      lfa = new ModelRenderer(this, 50, 86);
      lfa.addBox(-2F, 8F, -3.1F, 5, 4, 6);
      lfa.setRotationPoint(0F, 0F, 0F);
      lfa.setTextureSize(128, 128);
      lfa.mirror = true;
      setRotation(lfa, 0F, 0F, 0F);
      lfb = new ModelRenderer(this, 50, 75);
      lfb.addBox(-1.5F, 2.6F, -3.4F, 3, 8, 1);
      lfb.setRotationPoint(0F, 0F, 0F);
      lfb.setTextureSize(128, 128);
      lfb.mirror = true;
      setRotation(lfb, 0F, 0F, 0F);
      
      
      bipedHead.addChild(ha);
      bipedHead.addChild(hb);
      bipedHead.addChild(hc);
      bipedHead.addChild(hd);
      bipedHead.addChild(he);
      bipedHead.addChild(hf);
      bipedHead.addChild(hg);
      bipedHead.addChild(hh);
      bipedHead.addChild(hi);
      bipedHead.addChild(hj);
      bipedHead.addChild(hk);
      bipedHead.addChild(hl);
      bipedHead.addChild(hm);
      bipedHead.addChild(hn);
      bipedHead.addChild(ho);
      bipedHead.addChild(hp);
      bipedHead.addChild(hq);
      bipedHead.addChild(hr);
      bipedHead.addChild(hs);
      bipedHead.addChild(ht);
      bipedHead.addChild(hu);
      bipedHead.addChild(hv);
      bipedHead.addChild(hw);
      bipedHead.addChild(hx);
      bipedHead.addChild(hy);
      bipedHead.addChild(hz);
      bipedHead.addChild(h1);
      bipedHead.addChild(h2);
      bipedBody.addChild(ba);
      bipedBody.addChild(bd);
      bipedBody.addChild(bb);
      bipedBody.addChild(bc);
      bipedBody.addChild(be);
      bipedBody.addChild(bf);
      bipedBody.addChild(bg);
      bipedBody.addChild(bj);
      bipedBody.addChild(bi);
      bipedLeftArm.addChild(la);
      bipedLeftArm.addChild(lb);
      bipedLeftArm.addChild(lc);
      bipedLeftArm.addChild(ld);
      bipedLeftArm.addChild(le);
      bipedLeftArm.addChild(lf);
      bipedLeftArm.addChild(lg);
      bipedLeftArm.addChild(lh);
      bipedLeftArm.addChild(li);
      bipedLeftArm.addChild(ll);
      bipedLeftArm.addChild(lj);
      bipedRightArm.addChild(ra);
      bipedRightArm.addChild(rb);
      bipedRightArm.addChild(rc);
      bipedRightArm.addChild(rd);
      bipedRightArm.addChild(re);
      bipedRightArm.addChild(rf);
      bipedRightArm.addChild(rg);
      bipedRightArm.addChild(rh);
      bipedLeftLeg.addChild(lfa);
      bipedLeftLeg.addChild(lfb);
      bipedRightLeg.addChild(rfa);
      bipedRightLeg.addChild(rfb);
     
      
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
   
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
