language: java
cache:
directories:
- $HOME/.gradle
- .gradle
sudo: false
notifications:
  email: false
install: true
jdk:
  - oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace
script: ./gradlew build
