package mhfc.net.client.model.armor.community;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Model_ST_1_Bionic extends ModelBiped
{
  //fields
    ModelRenderer ha;
    ModelRenderer hb;
    ModelRenderer hc;
    ModelRenderer hd;
    ModelRenderer he;
    ModelRenderer hf;
    ModelRenderer hg;
    ModelRenderer ba;
    ModelRenderer bb;
    ModelRenderer bc;
    ModelRenderer bd;
    ModelRenderer be;
    ModelRenderer bf;
    ModelRenderer bg;
    ModelRenderer bh;
    ModelRenderer bi;
    ModelRenderer bj;
    ModelRenderer bk;
    ModelRenderer bl;
    ModelRenderer bm;
    ModelRenderer la;
    ModelRenderer lb;
    ModelRenderer lc;
    ModelRenderer ld;
    ModelRenderer le;
    ModelRenderer lf;
    ModelRenderer lg;
    ModelRenderer lh;
    ModelRenderer li;
    ModelRenderer lj;
    ModelRenderer ra;
    ModelRenderer rb;
    ModelRenderer rc;
    ModelRenderer rd;
    ModelRenderer re;
    ModelRenderer rf;
    ModelRenderer rg;
    ModelRenderer rh;
    ModelRenderer lfa;
    ModelRenderer lfb;
    ModelRenderer lfc;
    ModelRenderer lfd;
    ModelRenderer lfe;
    ModelRenderer rfa;
    ModelRenderer rfb;
    ModelRenderer rfc;
    ModelRenderer rfd;
    ModelRenderer rfe;
  
  public Model_ST_1_Bionic(float f)
  {
	  super(f, 0, 128, 128);
	  textureWidth = 128;
	  textureHeight = 128;
      ha = new ModelRenderer(this, 0, 97);
      ha.addBox(-4.5F, -7.5F, -6.5F, 9, 4, 1);
      ha.setRotationPoint(0F, 0F, 0F);
      ha.setTextureSize(128, 128);
      ha.mirror = true;
      setRotation(ha, -0.2617994F, 0F, 0F);
      hb = new ModelRenderer(this, 0, 39);
      hb.addBox(-2.5F, -5F, -4.5F, 5, 1, 1);
      hb.setRotationPoint(0F, 0F, 0F);
      hb.setTextureSize(128, 128);
      hb.mirror = true;
      setRotation(hb, 0F, 0F, 0F);
      hc = new ModelRenderer(this, 0, 43);
      hc.addBox(1.8F, -12.4F, -7F, 2, 8, 3);
      hc.setRotationPoint(0F, 0F, 0F);
      hc.setTextureSize(128, 128);
      hc.mirror = true;
      setRotation(hc, -0.2617994F, 0F, 0F);
      hd = new ModelRenderer(this, 0, 55);
      hd.addBox(-3.8F, -12.4F, -7F, 2, 8, 3);
      hd.setRotationPoint(0F, 0F, 0F);
      hd.setTextureSize(128, 128);
      hd.mirror = true;
      setRotation(hd, -0.2617994F, 0F, 0F);
      he = new ModelRenderer(this, 0, 68);
      he.addBox(-1F, -12.3F, -4.5F, 2, 4, 10);
      he.setRotationPoint(0F, 0F, 0F);
      he.setTextureSize(128, 128);
      he.mirror = true;
      setRotation(he, 0.1570796F, 0F, 0F);
      hf = new ModelRenderer(this, 0, 84);
      hf.addBox(-4.5F, -4F, -5F, 9, 4, 3);
      hf.setRotationPoint(0F, 0F, 0F);
      hf.setTextureSize(128, 128);
      hf.mirror = true;
      setRotation(hf, 0.2443461F, 0F, 0F);
      hg = new ModelRenderer(this, 0, 93);
      hg.addBox(-1.5F, -5.5F, -3.5F, 3, 1, 1);
      hg.setRotationPoint(0F, 0F, 0F);
      hg.setTextureSize(128, 128);
      hg.mirror = true;
      setRotation(hg, 0.2443461F, 0F, 0F);
      ba = new ModelRenderer(this, 27, 34);
      ba.addBox(-4F, 1F, -3F, 8, 1, 1);
      ba.setRotationPoint(0F, 0F, 0F);
      ba.setTextureSize(128, 128);
      ba.mirror = true;
      setRotation(ba, 0F, 0F, 0F);
      bb = new ModelRenderer(this, 27, 37);
      bb.addBox(-2.5F, 1F, -4F, 5, 4, 2);
      bb.setRotationPoint(0F, 0F, 0F);
      bb.setTextureSize(128, 128);
      bb.mirror = true;
      setRotation(bb, 0F, 0F, 0F);
      bc = new ModelRenderer(this, 27, 44);
      bc.addBox(-3F, 1F, -4.5F, 2, 1, 1);
      bc.setRotationPoint(0F, 0F, 0F);
      bc.setTextureSize(128, 128);
      bc.mirror = true;
      setRotation(bc, 0F, 0F, 0F);
      bd = new ModelRenderer(this, 27, 44);
      bd.addBox(1F, 1F, -4.5F, 2, 1, 1);
      bd.setRotationPoint(0F, 0F, 0F);
      bd.setTextureSize(128, 128);
      bd.mirror = true;
      setRotation(bd, 0F, 0F, 0F);
      be = new ModelRenderer(this, 27, 44);
      be.addBox(-3F, 2.5F, -4.5F, 2, 1, 1);
      be.setRotationPoint(0F, 0F, 0F);
      be.setTextureSize(128, 128);
      be.mirror = true;
      setRotation(be, 0F, 0F, 0F);
      bf = new ModelRenderer(this, 27, 44);
      bf.addBox(-3F, 4F, -4.5F, 2, 1, 1);
      bf.setRotationPoint(0F, 0F, 0F);
      bf.setTextureSize(128, 128);
      bf.mirror = true;
      setRotation(bf, 0F, 0F, 0F);
      bg = new ModelRenderer(this, 27, 44);
      bg.addBox(1F, 2.5F, -4.5F, 2, 1, 1);
      bg.setRotationPoint(0F, 0F, 0F);
      bg.setTextureSize(128, 128);
      bg.mirror = true;
      setRotation(bg, 0F, 0F, 0F);
      bh = new ModelRenderer(this, 27, 44);
      bh.addBox(1F, 4F, -4.5F, 2, 1, 1);
      bh.setRotationPoint(0F, 0F, 0F);
      bh.setTextureSize(128, 128);
      bh.mirror = true;
      setRotation(bh, 0F, 0F, 0F);
      bi = new ModelRenderer(this, 27, 47);
      bi.addBox(-2F, 8F, -3F, 4, 1, 1);
      bi.setRotationPoint(0F, 0F, 0F);
      bi.setTextureSize(128, 128);
      bi.mirror = true;
      setRotation(bi, 0F, 0F, 0F);
      bj = new ModelRenderer(this, 27, 50);
      bj.addBox(-1.5F, 5F, -3.5F, 1, 4, 1);
      bj.setRotationPoint(0F, 0F, 0F);
      bj.setTextureSize(128, 128);
      bj.mirror = true;
      setRotation(bj, 0F, 0F, 0F);
      bk = new ModelRenderer(this, 27, 50);
      bk.addBox(0.5F, 5F, -3.5F, 1, 4, 1);
      bk.setRotationPoint(0F, 0F, 0F);
      bk.setTextureSize(128, 128);
      bk.mirror = true;
      setRotation(bk, 0F, 0F, 0F);
      bl = new ModelRenderer(this, 42, 38);
      bl.addBox(-2.8F, 2.5F, -3.9F, 1, 1, 2);
      bl.setRotationPoint(0F, 0F, 0F);
      bl.setTextureSize(128, 128);
      bl.mirror = true;
      setRotation(bl, 0F, 0F, 0F);
      bm = new ModelRenderer(this, 42, 38);
      bm.addBox(-2.8F, 4.1F, -3.9F, 1, 1, 2);
      bm.setRotationPoint(0F, 0F, 0F);
      bm.setTextureSize(128, 128);
      bm.mirror = true;
      setRotation(bm, 0F, 0F, 0F);
      la = new ModelRenderer(this, 27, 56);
      la.addBox(-1F, -2.4F, -3F, 5, 4, 1);
      la.setRotationPoint(0F, 0F, 0F);
      la.setTextureSize(128, 128);
      la.mirror = true;
      setRotation(la, 0F, 0F, 0F);
      lb = new ModelRenderer(this, 27, 56);
      lb.addBox(-1F, -2.4F, 2F, 5, 4, 1);
      lb.setRotationPoint(0F, 0F, 0F);
      lb.setTextureSize(128, 128);
      lb.mirror = true;
      setRotation(lb, 0F, 0F, 0F);
      lc = new ModelRenderer(this, 27, 63);
      lc.addBox(3.1F, -1.4F, -2.6F, 1, 2, 5);
      lc.setRotationPoint(0F, 0F, 0F);
      lc.setTextureSize(128, 128);
      lc.mirror = true;
      setRotation(lc, 0F, 0F, 0F);
      ld = new ModelRenderer(this, 27, 72);
      ld.addBox(-0.5F, 1.5F, -2.5F, 3, 8, 1);
      ld.setRotationPoint(0F, 0F, 0F);
      ld.setTextureSize(128, 128);
      ld.mirror = true;
      setRotation(ld, 0F, 0F, 0F);
      le = new ModelRenderer(this, 27, 82);
      le.addBox(0F, 7.5F, -2.7F, 1, 3, 1);
      le.setRotationPoint(0F, 0F, 0F);
      le.setTextureSize(128, 128);
      le.mirror = true;
      setRotation(le, 0F, 0F, 0F);
      lf = new ModelRenderer(this, 27, 72);
      lf.addBox(-0.5F, 1.5F, 1.5F, 3, 8, 1);
      lf.setRotationPoint(0F, 0F, 0F);
      lf.setTextureSize(128, 128);
      lf.mirror = true;
      setRotation(lf, 0F, 0F, 0F);
      lg = new ModelRenderer(this, 27, 88);
      lg.addBox(2.5F, 0F, -1.5F, 1, 9, 3);
      lg.setRotationPoint(0F, 0F, 0F);
      lg.setTextureSize(128, 128);
      lg.mirror = true;
      setRotation(lg, 0F, 0F, 0F);
      lh = new ModelRenderer(this, 27, 82);
      lh.addBox(0F, 7.5F, 1.7F, 1, 3, 1);
      lh.setRotationPoint(0F, 0F, 0F);
      lh.setTextureSize(128, 128);
      lh.mirror = true;
      setRotation(lh, 0F, 0F, 0F);
      li = new ModelRenderer(this, 27, 82);
      li.addBox(3F, 7.5F, -0.5F, 1, 3, 1);
      li.setRotationPoint(0F, 0F, 0F);
      li.setTextureSize(128, 128);
      li.mirror = true;
      setRotation(li, 0F, 0F, 0F);
      lj = new ModelRenderer(this, 27, 102);
      lj.addBox(0.5F, -4F, -3.5F, 1, 3, 8);
      lj.setRotationPoint(0F, 0F, 0F);
      lj.setTextureSize(128, 128);
      lj.mirror = true;
      setRotation(lj, 0F, 0F, 0F);
      ra = new ModelRenderer(this, 27, 56);
      ra.addBox(-4F, -2.4F, -3F, 5, 4, 1);
      ra.setRotationPoint(0F, 0F, 0F);
      ra.setTextureSize(128, 128);
      ra.mirror = true;
      setRotation(ra, 0F, 0F, 0F);
      rb = new ModelRenderer(this, 27, 56);
      rb.addBox(-4F, -2.4F, 2F, 5, 4, 1);
      rb.setRotationPoint(0F, 0F, 0F);
      rb.setTextureSize(128, 128);
      rb.mirror = true;
      setRotation(rb, 0F, 0F, 0F);
      rc = new ModelRenderer(this, 42, 44);
      rc.addBox(-2.5F, -2.5F, -4F, 3, 1, 8);
      rc.setRotationPoint(0F, 0F, 0F);
      rc.setTextureSize(128, 128);
      rc.mirror = true;
      setRotation(rc, 0F, 0F, 0F);
      rd = new ModelRenderer(this, 42, 54);
      rd.addBox(-2F, -6F, -1.5F, 2, 4, 3);
      rd.setRotationPoint(0F, 0F, 0F);
      rd.setTextureSize(128, 128);
      rd.mirror = true;
      setRotation(rd, 0F, 0F, 0F);
      re = new ModelRenderer(this, 42, 63);
      re.addBox(-5F, -5F, -1F, 4, 1, 2);
      re.setRotationPoint(0F, 0F, 0F);
      re.setTextureSize(128, 128);
      re.mirror = true;
      setRotation(re, 0F, 0.6108652F, 0F);
      rf = new ModelRenderer(this, 42, 63);
      rf.addBox(-5F, -5F, -1F, 4, 1, 2);
      rf.setRotationPoint(0F, 0F, 0F);
      rf.setTextureSize(128, 128);
      rf.mirror = true;
      setRotation(rf, 0F, -0.6108652F, 0F);
      rg = new ModelRenderer(this, 42, 68);
      rg.addBox(-6F, -7F, -1F, 1, 3, 2);
      rg.setRotationPoint(0F, 0F, 0F);
      rg.setTextureSize(128, 128);
      rg.mirror = true;
      setRotation(rg, 0F, 0.6108652F, 0F);
      rh = new ModelRenderer(this, 42, 68);
      rh.addBox(-6F, -7F, -1F, 1, 3, 2);
      rh.setRotationPoint(0F, 0F, 0F);
      rh.setTextureSize(128, 128);
      rh.mirror = true;
      setRotation(rh, 0F, -0.6108652F, 0F);
      lfa = new ModelRenderer(this, 0, 105);
      lfa.addBox(2F, 11F, -6F, 1, 1, 2);
      lfa.setRotationPoint(0F, 0F, 0F);
      lfa.setTextureSize(128, 128);
      lfa.mirror = true;
      setRotation(lfa, 0F, 0F, 0F);
      lfb = new ModelRenderer(this, 0, 110);
      lfb.addBox(-2F, 9F, -3F, 5, 1, 6);
      lfb.setRotationPoint(0F, 0F, 0F);
      lfb.setTextureSize(128, 128);
      lfb.mirror = true;
      setRotation(lfb, 0F, 0F, 0F);
      lfc = new ModelRenderer(this, 40, 90);
      lfc.addBox(-2F, 10F, -4F, 5, 2, 7);
      lfc.setRotationPoint(0F, 0F, 0F);
      lfc.setTextureSize(128, 128);
      lfc.mirror = true;
      setRotation(lfc, 0F, 0F, 0F);
      lfd = new ModelRenderer(this, 0, 105);
      lfd.addBox(-1.8F, 11F, -6F, 1, 1, 2);
      lfd.setRotationPoint(0F, 0F, 0F);
      lfd.setTextureSize(128, 128);
      lfd.mirror = true;
      setRotation(lfd, 0F, 0F, 0F);
      lfe = new ModelRenderer(this, 0, 105);
      lfe.addBox(0.2F, 11F, -6F, 1, 1, 2);
      lfe.setRotationPoint(0F, 0F, 0F);
      lfe.setTextureSize(128, 128);
      lfe.mirror = true;
      setRotation(lfe, 0F, 0F, 0F);
      rfa = new ModelRenderer(this, 0, 105);
      rfa.addBox(0.8F, 11F, -6F, 1, 1, 2);
      rfa.setRotationPoint(0F, 0F, 0F);
      rfa.setTextureSize(128, 128);
      rfa.mirror = true;
      setRotation(rfa, 0F, 0F, 0F);
      rfb = new ModelRenderer(this, 0, 105);
      rfb.addBox(-1.2F, 11F, -6F, 1, 1, 2);
      rfb.setRotationPoint(0F, 0F, 0F);
      rfb.setTextureSize(128, 128);
      rfb.mirror = true;
      setRotation(rfb, 0F, 0F, 0F);
      rfc = new ModelRenderer(this, 0, 105);
      rfc.addBox(-3F, 11F, -6F, 1, 1, 2);
      rfc.setRotationPoint(0F, 0F, 0F);
      rfc.setTextureSize(128, 128);
      rfc.mirror = true;
      setRotation(rfc, 0F, 0F, 0F);
      rfd = new ModelRenderer(this, 0, 110);
      rfd.addBox(-3F, 9F, -3F, 5, 1, 6);
      rfd.setRotationPoint(0F, 0F, 0F);
      rfd.setTextureSize(128, 128);
      rfd.mirror = true;
      setRotation(rfd, 0F, 0F, 0F);
      rfe = new ModelRenderer(this, 40, 90);
      rfe.addBox(-3F, 10F, -4F, 5, 2, 7);
      rfe.setRotationPoint(0F, 0F, 0F);
      rfe.setTextureSize(128, 128);
      rfe.mirror = true;
      setRotation(rfe, 0F, 0F, 0F);
      
      bipedHead.addChild(ha);
      bipedHead.addChild(hb);
      bipedHead.addChild(hc);
      bipedHead.addChild(hd);
      bipedHead.addChild(he);
      bipedHead.addChild(hf);
      bipedHead.addChild(hg);
      bipedBody.addChild(ba);
      bipedBody.addChild(bb);
      bipedBody.addChild(bc);
      bipedBody.addChild(bd);
      bipedBody.addChild(be);
      bipedBody.addChild(bf);
      bipedBody.addChild(bg);
      bipedBody.addChild(bh);
      bipedBody.addChild(bi);
      bipedBody.addChild(bj);
      bipedBody.addChild(bk);
      bipedBody.addChild(bl);
      bipedBody.addChild(bm);
      bipedLeftArm.addChild(la);
      bipedLeftArm.addChild(lb);
      bipedLeftArm.addChild(lc);
      bipedLeftArm.addChild(ld);
      bipedLeftArm.addChild(le);
      bipedLeftArm.addChild(lf);
      bipedLeftArm.addChild(lg);
      bipedLeftArm.addChild(lh);
      bipedLeftArm.addChild(li);
      bipedLeftArm.addChild(lj);
      bipedRightArm.addChild(ra);
      bipedRightArm.addChild(rb);
      bipedRightArm.addChild(rc);
      bipedRightArm.addChild(rd);
      bipedRightArm.addChild(re);
      bipedRightArm.addChild(rf);
      bipedRightArm.addChild(rg);
      bipedRightArm.addChild(rh);
      bipedLeftLeg.addChild(lfa);
      bipedLeftLeg.addChild(lfb);
      bipedLeftLeg.addChild(lfc);
      bipedLeftLeg.addChild(lfd);
      bipedLeftLeg.addChild(lfe);
      bipedRightLeg.addChild(rfa);
      bipedRightLeg.addChild(rfb);
      bipedRightLeg.addChild(rfc);
      bipedRightLeg.addChild(rfd);
      bipedRightLeg.addChild(rfe);
      
      
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
